[package]
name = "guardarFileScanner"
version = "1.2"
edition = "2025 - Summer Edition"

[dependencies]
mlua = "0.9"
log = "0.4"
env_logger = "0.10"
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
csv = "1.2"
dirs = "5.0"